[tool.ruff]
# See https://beta.ruff.rs/docs/rules/
select = ["E", "F", "B", "UP", "C90", "RUF"]
# B028: Ignore explicit stacklevel`
# RUF013: Too many false positives (implicit optional)
# UP007: Changes Union to | which breaks pyrallis
ignore = ["B028", "RUF013", "UP007"]

# Exclude a variety of commonly ignored directories.
exclude = [
    "*.egg-info",
    "__pycache__",
    ".eggs",
    ".git",
    "venv",
    "wandb",
    "log/",
    "runs/",
    ".ruff_cache",
    ".mypy_cache"
]

# Same as Black.
line-length = 127

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10
target-version = "py311"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 15

[tool.black]
line-length = 127

[tool.isort]
profile = "black"
line_length = 127

[tool.mypy]
# We don't use mypy
# ignore_missing_imports = true
# follow_imports = "silent"
# show_error_codes = true
# exclude = """(?x)(
#     put_some_ignored_files_here.py$
#     | and_more_here_with_the_bar.py$
#   )"""